services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE}
        VITE_SPOTIFY_ID: ${VITE_SPOTIFY_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}

  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      SPOTIFY_ID: ${SPOTIFY_ID}
      REDIRECT_URI: ${REDIRECT_URI}
